### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ranjanan** [JunoLab/Hiccup.jl#17]
On v0.5, tests don't pass, but on master it does. Could you tag a new release please?

**Comment by MikeInnes** [comment]
I gave you commit access – knock yourself out.

**Comment by ranjanan** [comment]
Thanks!

**Comment by andreasnoack** [comment]
bump

**Comment by andreasnoack** [comment]
@MikeInnes @ranjanan Could either of you tag again please. `Lazy.jl` is failing on master and right now `DataFrames` depends on `Lazy.jl`.

**Comment by ararslan** [comment]
Sorry this is a little off topic, but [this](https://github.com/MikeInnes/Lazy.jl/pull/58) should fix the issue with Lazy.jl. Once that's merged and the package tagged, pretty much everything that depends on Lazy should bump their required Lazy versions. DataFrames doesn't depend directly on Lazy; it only does so indirectly via a test dependency on Atom.jl.

**Comment by andreasnoack** [comment]
@ararslan The dependency on `Atom` is not just a [test dependency](https://github.com/JuliaStats/DataFrames.jl/blob/master/REQUIRE#L10). Also `Hiccup` [doesn't depend on `Lazy` anymore](https://github.com/JunoLab/Hiccup.jl/commit/099533fa86d3997ebbeacd4f8dc4aee579f6ce5c). The problem was that `Hiccup` hadn't been tagged since that change.

**Comment by ViralBShah** [comment]
Close?
